import React from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { ArrowLeft, Share2, FileText, Activity, Shield, Download, CheckCircle, AlertTriangle, Info, Settings, MousePointer2 } from 'lucide-react';

const FinalReportScreen = () => {
    const location = useLocation();
    const navigate = useNavigate();
    const result = location.state?.result;

    const data = result || {
        drug_overview: { name: "Metformin derivative", smiles: "CN(C)C(=N)NC(=N)N" },
        risk_summary: { level: "LOW TOXICITY", risk_percentage: 22 },
        ai_confidence: 98.8
    };

    return (
        <div className="dashboard-container" style={{ backgroundColor: '#F8FAFC' }}>
            {/* Header Nav */}
            <div style={{ 
                width: '100%', 
                background: 'linear-gradient(90deg, #0D9488, #14B8A6)', 
                padding: '16px 20px', 
                color: 'white',
                display: 'flex',
                alignItems: 'center',
                justifyContent: 'space-between'
            }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 16 }}>
                    <button onClick={() => navigate(-1)} style={{ background: 'none', border: 'none', color: 'white', cursor: 'pointer' }}>
                        <ArrowLeft size={24} />
                    </button>
                    <span style={{ fontSize: 18, fontWeight: 700 }}>Final Report</span>
                </div>
                <button style={{ background: 'none', border: 'none', color: 'white', cursor: 'pointer' }}>
                    <Share2 size={24} />
                </button>
            </div>

            <div className="dashboard-content" style={{ padding: '16px 20px 40px' }}>
                {/* Summary Card */}
                <div style={{ 
                    background: 'linear-gradient(135deg, #3B82F6, #0D9488)',
                    borderRadius: 16,
                    padding: 20,
                    color: 'white',
                    marginBottom: 24
                }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 12, marginBottom: 20 }}>
                        <div style={{ background: 'rgba(255,255,255,0.2)', padding: 8, borderRadius: 8 }}>
                            <FileText size={24} />
                        </div>
                        <div>
                            <div style={{ fontWeight: 800, fontSize: 18 }}>Analysis Report</div>
                            <div style={{ fontSize: 12, opacity: 0.8 }}>Generated by Molecular AI</div>
                        </div>
                    </div>
                    <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
                        <SummaryItem label="Compound" value={data.drug_overview.name} />
                        <SummaryItem label="SMILES ID" value={data.drug_overview.smiles} isSmall />
                        <SummaryItem label="Date" value="February 22, 2024" />
                        <SummaryItem label="Verified By" value="Molecular AI V2.4" />
                    </div>
                </div>

                {/* Executive Summary Grid */}
                <h3 style={{ fontSize: 18, fontWeight: 800, marginBottom: 16, display: 'flex', alignItems: 'center', gap: 8 }}>
                    <Activity size={20} color="#10B981" />
                    Executive Summary
                </h3>
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 12, marginBottom: 24 }}>
                    <MiniStatCard label="Toxicity Category" val1="LOW" val2="TOXICITY" val3={`${data.risk_summary.risk_percentage}%`} bg="#ECFDF5" color="#059669" />
                    <MiniStatCard label="Critical Risk" val1="SCORE" val2="LOW" val3="18/100" bg="#EFF6FF" color="#2563EB" />
                    <MiniStatCard label="AI Confidence" val1="SCORE" val2={`${data.ai_confidence}%`} val3="HIGH" bg="#F5F3FF" color="#7C3AED" />
                    <MiniStatCard label="Therapeutic Index" val1="SCORE" val2="8.0" val3="INDEX" bg="#FFF7ED" color="#EA580C" />
                </div>

                {/* Recommendation Banner */}
                <div style={{ backgroundColor: '#10B981', color: 'white', padding: 12, borderRadius: 8, display: 'flex', alignItems: 'center', gap: 8, marginBottom: 24 }}>
                    <CheckCircle size={16} />
                    <span style={{ fontSize: 11, fontWeight: 800, letterSpacing: 0.5 }}>THE COMPOUND IS RECOMMENDED FOR CLINICAL TRIAL PHASE-I</span>
                </div>

                {/* Report Sections */}
                <ReportSection title="Toxicity Profile" icon={AlertTriangle} color="#10B981" items={[
                    `Overall Classification: ${data.risk_summary.level} (${data.risk_summary.risk_percentage}% Risk Score)`,
                    "Low Hepatotoxicity: Minimal liver enzyme elevation detected.",
                    "Reduced Renal Risk: Markers within safe therapeutic range."
                ]} bg="#ECFDF5" />

                <ReportSection title="Protein Regulation" icon={Settings} color="#3B82F6" items={[
                    "Upregulated: GLUT4 (+46%) - Enhanced glucose uptake.",
                    "Upregulated: IRS-1 (+38%) - Improved signaling.",
                    "Downregulated: DGPase (-42%) - Reduced production."
                ]} bg="#EFF6FF" />

                {/* Download Button */}
                <button className="primary-btn" style={{ background: 'linear-gradient(90deg, #C026D3, #DB2777)', marginBottom: 16 }}>
                    <Download size={20} />
                    <span>Download Final Report PDF</span>
                </button>

                <button 
                  onClick={() => navigate('/analysis')}
                  className="primary-btn" 
                  style={{ background: '#1E293B' }}
                >
                    <span>Start New Study</span>
                </button>
            </div>
        </div>
    );
};

const SummaryItem = ({ label, value, isSmall }) => (
    <div>
        <div style={{ fontSize: 11, opacity: 0.7, marginBottom: 2 }}>{label}</div>
        <div style={{ fontSize: isSmall ? 11 : 14, fontWeight: 700 }}>{value}</div>
    </div>
);

const MiniStatCard = ({ label, val1, val2, val3, bg, color }) => (
    <div style={{ backgroundColor: bg, color, padding: 12, borderRadius: 12 }}>
        <div style={{ fontSize: 10, opacity: 0.7, marginBottom: 4 }}>{label}</div>
        <div style={{ fontSize: 16, fontWeight: 900 }}>{val1}</div>
        <div style={{ fontSize: 14, fontWeight: 700 }}>{val2}</div>
        <div style={{ fontSize: 18, fontWeight: 900, marginTop: 4 }}>{val3}</div>
    </div>
);

const ReportSection = ({ title, icon: Icon, color, items, bg }) => (
    <div style={{ marginBottom: 24 }}>
        <h4 style={{ display: 'flex', alignItems: 'center', gap: 8, fontSize: 16, fontWeight: 800, marginBottom: 12 }}>
            <Icon size={20} color={color} />
            {title}
        </h4>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
            {items.map((item, i) => (
                <div key={i} style={{ backgroundColor: bg, padding: 12, borderRadius: 8, display: 'flex', alignItems: 'center', gap: 10 }}>
                    <CheckCircle size={14} color={color} />
                    <span style={{ fontSize: 13, color: '#334155' }}>{item}</span>
                </div>
            ))}
        </div>
    </div>
);

export default FinalReportScreen;
